#!/bin/bash

_commandList ()
{
    echo "codecept:convert-selenium-id-for-codecept"
    echo "magento2:check-templates"
    echo "magento2:class-from-path"
    echo "magento2:convert-class"
    echo "magento2:convert-observers-xml"
    echo "magento2:convert-system-xml"
    echo "magento2:extract-mage2-system-xml-paths"
    echo "magento2:fix-direct-om"
    echo "magento2:fix-permissions-modphp"
    echo "magento2:path-from-class"
    echo "magento2:read-rest-schema"
    echo "magento2:generate:acl"
    echo "magento2:generate:acl:change-title"
    echo "magento2:generate:command"
    echo "magento2:generate:config-helper"
    echo "magento2:generate:controller-edit-acl"
    echo "magento2:generate:crud-model"
    echo "magento2:generate:di"
    echo "magento2:generate:full-module"
    echo "magento2:generate:install"
    echo "magento2:generate:menu"
    echo "magento2:generate:module"
    echo "magento2:generate:observer"
    echo "magento2:generate:plugin-xml"
    echo "magento2:generate:preference"
    echo "magento2:generate:psr-log-level"
    echo "magento2:generate:registration"
    echo "magento2:generate:remove-named-node"
    echo "magento2:generate:route"
    echo "magento2:generate:schema-upgrade"
    echo "magento2:generate:theme"
    echo "magento2:generate:ui:add-column-text"
    echo "magento2:generate:ui:add-form-field"
    echo "magento2:generate:ui:add-schema-column"
    echo "magento2:generate:ui:add-to-layout"
    echo "magento2:generate:ui:form"
    echo "magento2:generate:ui:grid"
    echo "magento2:generate:view"
    echo "magento2:scan:acl-used"
    echo "magento2:scan:class-and-namespace"
    echo "magento2:scan:htaccess"
    echo "magento2:scan:registration"
    echo "magento2:search:search-controllers"
    echo "nexmo:send-text"
    echo "nexmo:store-credentials"
    echo "nexmo:verify-request"
    echo "nexmo:verify-sendcode"
    echo "parsing:citicard"
    echo "parsing:csv-to-iif"
    echo "parsing:wf"
    echo "pestle:baz-bar"
    echo "pestle:build-command-list"
    echo "pestle:clear-cache"
    echo "pestle:dev-import"
    echo "pestle:dev-namespace"
    echo "pestle:export-as-symfony"
    echo "pestle:export-module"
    echo "pestle:foo-bar"
    echo "pestle:generate-command"
    echo "pestle:hello-argument"
    echo "pestle:pestle-run-file"
    echo "php:extract-session"
    echo "php:format-php"
    echo "php:test-namespace-integrity"
    echo "pulsestorm:build-book"
    echo "pulsestorm:md-to-say"
    echo "pulsestorm:monty-hall-problem"
    echo "pulsestorm:orphan-content"
    echo "pulsestorm:pandoc-md"
    echo "pulsestorm:tax-estimate"
    echo "twitter:api:oauth"
    echo "hello-world"
    echo "help"
    echo "list-commands"
    echo "selfupdate"
    echo "test-output"
    echo "testbed"
    echo "version"
    echo "wordpress:export:xml"
    echo "wordpress:parse:urls"

    return 0;
}

_pestleAutocomplete ()
{
    local cur
    local all
    _get_comp_words_by_ref -n : cur
    all=$(_commandList)
    COMPREPLY=( $(compgen -W "$all" $cur) )
    __ltrim_colon_completions "$cur"
    return 0
}
complete -F _pestleAutocomplete -o filenames pestle.phar